> Introdução à Ciência dos Dados \
> Ciência da Computação – UFV/Florestal


* **Nome:** Miguel Antonio Ribeiro e Silva
* **Matrícula:**  4680

# Aula Prática 01
##  Conhecendo o Ambiente e Manipulando Estruturas de Uma Dimensão

**Objetivo:** Conhecer o ambiente de desenvolvimento \
**Pré-requisitos:** Linguagem de programação Python \
**Meta:** Ao final da prática, o aluno será capaz de iniciar o ambiente de desenvolvimento e executar comandos na linguagem Python para manipular uma estrutura de dados de uma dimensão.

----

## Introdução

A ferramenta de desenvolvimento a ser utilizada é chamada Jupyter Notebook. Com ela, é possível executar comandos para análises de dados isoladamente, sem precisar executar todo o código sempre que for preciso fazer algum ajuste. Você pode instalar localmente na sua máquina o [Jupyter Notebook](https://jupyter.org) ou utilizar o [Google Colab](https://colab.research.google.com).

A principal API de desenvolvimento que será utilizada é chamada de [Pandas](https://pandas.pydata.org). Com ela, é possível manipular estruturas de dados complexas para análises de dados.

Dentro da API Pandas, uma estrutura 1-dimensional é a Series. Uma Serie é similar a um arranjo nas linguagens de programação, com algumas características particulares que a torna mais poderosa que as estruturas de arranjos e listas tradicionais.

Seguindo o roteiro abaixo, você deverá utilizar o Jupyter Notebook ou Google Colab para manipular algumas estruturas do tipo Series.

Para instalar as ferramentas e as bibliotecas necessárias, você pode seguir o tutorial que está no PVANet.

In [1]:
### NÃO REMOVA ESSA CÉLULA! ####
!pip install learntools_dados_ufv

Requirement already satisfied: learntools_dados_ufv in c:\users\miguel\anaconda3\lib\site-packages (1.0.10)

In [2]:
#### Não altere essa célula!!! ####
import pandas as pd
import numpy as np
import math
import random

from learntools_dados_ufv.core import binder; binder.bind(globals())
from learntools_dados_ufv.ccf425.pratica_1 import *

## 1. Gere uma Serie com 500 valores inteiros aleatórios entre -1000 e 1000
Armazene-o na variável `series`. 

Chame a função `q1.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q1.hint()`

In [3]:
# q1.hint()

rand = random.sample(range(-1000, 1000),500)
series = pd.Series(rand)
print(series)

q1.check()

0      662
1        4
2      320
3      272
4      573
      ...
495    361
496    852
497   -840
498    300
499    367
Length: 500, dtype: int64

CORRETO:

## 2. Recupere o maior valor da Série
Armazene-o na variável `series_max`. 

Chame a função `q2.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q2.hint()`

In [4]:
# q2.hint()

series_max = max(series)
print(series_max)

q2.check()

998

CORRETO:

## 3. Recupere o menor valor da Série
Armazene-o na variável `series_min`.

Chame a função `q3.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q3.hint()`

In [5]:
# q3.hint()

series_min = min(series)
print(series_min)

q3.check()

-998

CORRETO:

## 4. Recupere somente os valores positivos da Série
Armazene-os na variável `series_positives`.

Chame a função `q4.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q4.hint()`

In [6]:
# q4.hint()

series_positives =  series[series > 0]
print(series_positives)

q4.check()

0      662
1        4
2      320
3      272
4      573
      ...
486     17
495    361
496    852
498    300
499    367
Length: 232, dtype: int64

CORRETO:

## 5. Recupere somente os valores ímpares da Série
Armazene-os na variável `series_odds`.

Chame a função `q5.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q5.hint()`

In [7]:
# q5.hint()

series_odds = series[series % 2 != 0]
print(series_odds)

q5.check()

4      573
5     -249
7      909
8     -129
10     661
      ...
487   -533
492   -385
493   -217
495    361
499    367
Length: 238, dtype: int64

CORRETO:

## 6. Recupere somente os valores das posições/índices de 50 a 100 (inclusive) da Série
Armazene-os na variável `series_range`.

Chame a função `q6.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q6.hint(n)` onde n é o número da dica.

In [8]:
#q6.hint()


series_range = series[50:101]
print(series_range)

q6.check()

50    -199
51     504
52    -574
53     663
54      24
55     -62
56    -713
57     558
58     644
59    -397
60    -599
61     371
62    -582
63    -323
64    -296
65    -192
66     998
67     806
68    -382
69    -443
70    -883
71    -513
72    -421
73     833
74    -979
75    -915
76     827
77     959
78     582
79    -476
80     969
81    -982
82    -491
83    -392
84     421
85     -80
86    -911
87    -657
88    -424
89    -766
90    -171
91     751
92     489
93    -345
94     537
95    -134
96    -528
97    -335
98    -945
99      10
100    861
dtype: int64

CORRETO

## 7. Recupere a quantidade de valores pares da Série
Armazene-o na variável `series_even_size`.

Chame a função `q7.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q7.hint(n)` onde n é o número da dica.

In [9]:
# q7.hint()

series_even_size = len(series[series % 2 == 0])
print(series_even_size)

q7.check()

262

CORRETO:

## 8. Recupere a quantidade de valores da Série maiores que 500
Armazene-o na variável `series_high_values_size`.

Chame a função `q8.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q8.hint()` onde n é o número da dica.

In [10]:
# q8.hint()

series_high_values_size = len(series[series > 500])
print(series_high_values_size)

q8.check()

110

CORRETO:

## 9. Recupere os valores simultaneamente maiores que 500 e menores que 700 da Série
Armazene-o na variável `series_subset_values`.

Chame a função `q9.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q9.hint()` onde n é o número da dica.

In [11]:
# q9.hint()

series_subset_values = series[series > 500][series < 700]
print(series_subset_values)

q9.check()

0      662
4      573
10     661
23     542
31     625
36     653
39     563
51     504
53     663
57     558
58     644
78     582
94     537
103    680
116    574
119    655
135    509
158    547
171    588
182    637
184    630
224    687
233    606
241    667
255    596
282    592
290    597
300    532
315    559
327    656
332    645
335    520
339    508
343    668
354    566
355    586
358    546
362    598
364    600
368    617
414    673
422    536
428    671
477    515
482    516
dtype: int64

CORRETO:

## 10. Imprima a raiz quadrada de todos os valores da Série
Armazene-os na variável `series_sqrt_values`.

**Atenção**: Mantenha o tipo da série como `float64`. Os valores inválidos devem ser `NaN`.

Chame a função `q10.check()` no fim da célula para verificar a resposta.
Você pode pedir dicas com `q10.hint()` onde n é o número da dica.

In [12]:
q10.hint()

# Teve uns momentos que não funcionou

series_sqrt_values = series.apply(np.sqrt)
print(series_sqrt_values)

q10.check()

Dica: Talvez a função `pd.Series.apply` seja útil... Ou talvez você possa fazer operações matemáticas diretamente na série...

0      25.729361
1       2.000000
2      17.888544
3      16.492423
4      23.937418
         ...
495    19.000000
496    29.189039
497          NaN
498    17.320508
499    19.157244
Length: 500, dtype: float64

CORRETO:

## 11. Faça sua própria ~5ª~ série!

Agora é sua vez de brincar com as séries. E bem não é *exatamente* a 5ª série, mas é quase!

### 11.a.
Crie uma série (`pd.Series`) que possui os dados das notas de **todas** as turmas de 5ª série de **todas as disciplinas** de uma escola fictícia. Dê um nome pra essa escola e explique quantas disciplinas essas turmas cursam e quantos alunos possuem em cada sala.

Armazene a sua série na variável `grades`.

Chame a função `q11.a.check()` no fim da célula para verificar a resposta.
Você pode pedir dica com `q11.a.hint()`.

#### Resposta:

A escola municipal de Strawgoh possui em sua quinta série, 100 alunos, divididos em 5 turmas, cada uma com 20 alunos. As disciplinas são: Matemática, Português, Ciências, História e Geografia.
Para alocar as notas foi criado uma série de séries, grade , onde cada série de nota possui 5 notas de 0 a 10, sendo cada nota referente a uma disciplina, além da matrícula do aluno e sua turma.

### Série de alunos com suas respectivas matrículas de 4000 a 4099

In [13]:
alunos = pd.Series(range(4000, 4100))
print(alunos)

0     4000
1     4001
2     4002
3     4003
4     4004
      ...
95    4095
96    4096
97    4097
98    4098
99    4099
Length: 100, dtype: int64

### Série com as disciplinas estudadas na escola municipal de Strawgoh

In [14]:
disciplina = pd.Series(["MAT", "POR", "CIE", "HIS", "GEO"])
print(disciplina)

0    MAT
1    POR
2    CIE
3    HIS
4    GEO
dtype: object

### Criei uma série com séries de notas de cada aluno, com 5 notas de 0 a 10 em cada disciplina

In [15]:
notas = pd.Series([pd.Series(np.random.randint(0, 11, 5), index = disciplina) for i in range(100)])
for i in range(100):
    print("ALUNO: " + str(i))
    print(notas[i])

ALUNO: 0
MAT    6
POR    4
CIE    6
HIS    4
GEO    9
dtype: int32
ALUNO: 1
MAT     4
POR     8
CIE    10
HIS     3
GEO     0
dtype: int32
ALUNO: 2
MAT    9
POR    1
CIE    7
HIS    8
GEO    3
dtype: int32
ALUNO: 3
MAT    2
POR    1
CIE    6
HIS    3
GEO    5
dtype: int32
ALUNO: 4
MAT    1
POR    9
CIE    2
HIS    3
GEO    5
dtype: int32
ALUNO: 5
MAT    6
POR    6
CIE    2
HIS    0
GEO    4
dtype: int32
ALUNO: 6
MAT    4
POR    1
CIE    3
HIS    4
GEO    9
dtype: int32
ALUNO: 7
MAT    4
POR    4
CIE    8
HIS    6
GEO    0
dtype: int32
ALUNO: 8
MAT     4
POR     7
CIE     8
HIS    10
GEO     2
dtype: int32
ALUNO: 9
MAT     3
POR     1
CIE     1
HIS    10
GEO     0
dtype: int32
ALUNO: 10
MAT    1
POR    0
CIE    3
HIS    7
GEO    6
dtype: int32
ALUNO: 11
MAT     4
POR     1
CIE     1
HIS    10
GEO     6
dtype: int32
ALUNO: 12
MAT    10
POR    10
CIE     1
HIS     8
GEO    10
dtype: int32
ALUNO: 13
MAT    7
POR    9
CIE    5
HIS    6
GEO    1
dtype: int32
ALUNO: 14
MAT    0
POR    2
CIE    2
HIS    9
GEO    6
dtype: int32
ALUNO: 15
MAT     1
POR     6
CIE     1
HIS    10
GEO     8
dtype: int32
ALUNO: 16
MAT    3
POR    9
CIE    4
HIS    9
GEO    7
dtype: int32
ALUNO: 17
MAT    1
POR    3
CIE    4
HIS    2
GEO    1
dtype: int32
ALUNO: 18
MAT    7
POR    8
CIE    2
HIS    5
GEO    5
dtype: int32
ALUNO: 19
MAT    1
POR    1
CIE    4
HIS    7
GEO    8
dtype: int32
ALUNO: 20
MAT     4
POR    10
CIE    10
HIS     9
GEO     2
dtype: int32
ALUNO: 21
MAT     1
POR     1
CIE     4
HIS     4
GEO    10
dtype: int32
ALUNO: 22
MAT    7
POR    0
CIE    5
HIS    1
GEO    1
dtype: int32
ALUNO: 23
MAT    2
POR    1
CIE    1
HIS    5
GEO    1
dtype: int32
ALUNO: 24
MAT     4
POR     2
CIE    10
HIS     1
GEO     8
dtype: int32
ALUNO: 25
MAT     2
POR    10
CIE     4
HIS     9
GEO     6
dtype: int32
ALUNO: 26
MAT    10
POR     1
CIE     0
HIS     4
GEO     8
dtype: int32
ALUNO: 27
MAT    3
POR    7
CIE    1
HIS    1
GEO    6
dtype: int32
ALUNO: 28
MAT     4
POR     8
CIE    10
HIS    10
GEO     4
dtype: int32
ALUNO: 29
MAT    9
POR    3
CIE    9
HIS    7
GEO    6
dtype: int32
ALUNO: 30
MAT    8
POR    4
CIE    3
HIS    8
GEO    3
dtype: int32
ALUNO: 31
MAT     1
POR     9
CIE    10
HIS     6
GEO     5
dtype: int32
ALUNO: 32
MAT    6
POR    3
CIE    9
HIS    0
GEO    6
dtype: int32
ALUNO: 33
MAT    9
POR    7
CIE    6
HIS    2
GEO    1
dtype: int32
ALUNO: 34
MAT    1
POR    2
CIE    8
HIS    4
GEO    4
dtype: int32
ALUNO: 35
MAT    2
POR    0
CIE    1
HIS    3
GEO    9
dtype: int32
ALUNO: 36
MAT    3
POR    9
CIE    9
HIS    9
GEO    9
dtype: int32
ALUNO: 37
MAT    10
POR     3
CIE     9
HIS     2
GEO     7
dtype: int32
ALUNO: 38
MAT    6
POR    2
CIE    9
HIS    5
GEO    2
dtype: int32
ALUNO: 39
MAT     6
POR     5
CIE     1
HIS     4
GEO    10
dtype: int32
ALUNO: 40
MAT     7
POR     9
CIE     0
HIS    10
GEO    10
dtype: int32
ALUNO: 41
MAT     6
POR     1
CIE     8
HIS    10
GEO     5
dtype: int32
ALUNO: 42
MAT    2
POR    1
CIE    8
HIS    7
GEO    9
dtype: int32
ALUNO: 43
MAT    10
POR     6
CIE    10
HIS     2
GEO     6
dtype: int32
ALUNO: 44
MAT    3
POR    3
CIE    7
HIS    2
GEO    6
dtype: int32
ALUNO: 45
MAT    6
POR    4
CIE    9
HIS    2
GEO    5
dtype: int32
ALUNO: 46
MAT    5
POR    4
CIE    0
HIS    5
GEO    5
dtype: int32
ALUNO: 47
MAT    0
POR    0
CIE    1
HIS    1
GEO    2
dtype: int32
ALUNO: 48
MAT    9
POR    2
CIE    8
HIS    2
GEO    4
dtype: int32
ALUNO: 49
MAT    3
POR    9
CIE    6
HIS    4
GEO    8
dtype: int32
ALUNO: 50
MAT    9
POR    9
CIE    4
HIS    0
GEO    8
dtype: int32
ALUNO: 51
MAT    2
POR    5
CIE    9
HIS    7
GEO    7
dtype: int32
ALUNO: 52
MAT    2
POR    5
CIE    5
HIS    0
GEO    0
dtype: int32
ALUNO: 53
MAT    6
POR    6
CIE    3
HIS    1
GEO    3
dtype: int32
ALUNO: 54
MAT    1
POR    9
CIE    2
HIS    0
GEO    4
dtype: int32
ALUNO: 55
MAT     5
POR     3
CIE     5
HIS    10
GEO    10
dtype: int32
ALUNO: 56
MAT     3
POR     0
CIE     9
HIS     1
GEO    10
dtype: int32
ALUNO: 57
MAT     1
POR     6
CIE    10
HIS     3
GEO     5
dtype: int32
ALUNO: 58
MAT     8
POR    10
CIE     5
HIS     7
GEO     9
dtype: int32
ALUNO: 59
MAT    1
POR    0
CIE    9
HIS    1
GEO    9
dtype: int32
ALUNO: 60
MAT    3
POR    1
CIE    0
HIS    1
GEO    0
dtype: int32
ALUNO: 61
MAT     3
POR     5
CIE     9
HIS    10
GEO     4
dtype: int32
ALUNO: 62
MAT     3
POR     0
CIE     3
HIS    10
GEO     1
dtype: int32
ALUNO: 63
MAT    6
POR    1
CIE    7
HIS    3
GEO    4
dtype: int32
ALUNO: 64
MAT     8
POR     6
CIE     9
HIS     8
GEO    10
dtype: int32
ALUNO: 65
MAT    0
POR    4
CIE    4
HIS    9
GEO    3
dtype: int32
ALUNO: 66
MAT    4
POR    8
CIE    8
HIS    5
GEO    2
dtype: int32
ALUNO: 67
MAT    10
POR     8
CIE    10
HIS     1
GEO     1
dtype: int32
ALUNO: 68
MAT    4
POR    1
CIE    4
HIS    1
GEO    8
dtype: int32
ALUNO: 69
MAT     8
POR     1
CIE     2
HIS    10
GEO     9
dtype: int32
ALUNO: 70
MAT     3
POR     6
CIE    10
HIS     8
GEO     0
dtype: int32
ALUNO: 71
MAT    6
POR    6
CIE    7
HIS    8
GEO    3
dtype: int32
ALUNO: 72
MAT     6
POR     0
CIE     6
HIS     3
GEO    10
dtype: int32
ALUNO: 73
MAT     5
POR     7
CIE     3
HIS     3
GEO    10
dtype: int32
ALUNO: 74
MAT    5
POR    2
CIE    9
HIS    7
GEO    3
dtype: int32
ALUNO: 75
MAT    2
POR    4
CIE    3
HIS    5
GEO    9
dtype: int32
ALUNO: 76
MAT    3
POR    3
CIE    4
HIS    3
GEO    2
dtype: int32
ALUNO: 77
MAT    5
POR    8
CIE    9
HIS    2
GEO    1
dtype: int32
ALUNO: 78
MAT    8
POR    4
CIE    6
HIS    4
GEO    7
dtype: int32
ALUNO: 79
MAT    7
POR    5
CIE    8
HIS    8
GEO    9
dtype: int32
ALUNO: 80
MAT     5
POR     0
CIE    10
HIS     7
GEO    10
dtype: int32
ALUNO: 81
MAT    2
POR    8
CIE    0
HIS    6
GEO    5
dtype: int32
ALUNO: 82
MAT    2
POR    5
CIE    4
HIS    2
GEO    0
dtype: int32
ALUNO: 83
MAT     7
POR     1
CIE    10
HIS     5
GEO     6
dtype: int32
ALUNO: 84
MAT    3
POR    2
CIE    6
HIS    5
GEO    5
dtype: int32
ALUNO: 85
MAT    5
POR    8
CIE    9
HIS    2
GEO    3
dtype: int32
ALUNO: 86
MAT    8
POR    4
CIE    4
HIS    9
GEO    2
dtype: int32
ALUNO: 87
MAT    5
POR    3
CIE    9
HIS    9
GEO    3
dtype: int32
ALUNO: 88
MAT    4
POR    1
CIE    6
HIS    9
GEO    8
dtype: int32
ALUNO: 89
MAT    9
POR    9
CIE    3
HIS    7
GEO    2
dtype: int32
ALUNO: 90
MAT    10
POR    10
CIE     0
HIS     4
GEO     2
dtype: int32
ALUNO: 91
MAT     5
POR     2
CIE    10
HIS     3
GEO    10
dtype: int32
ALUNO: 92
MAT    2
POR    7
CIE    5
HIS    9
GEO    6
dtype: int32
ALUNO: 93
MAT    4
POR    8
CIE    7
HIS    7
GEO    8
dtype: int32
ALUNO: 94
MAT     0
POR     6
CIE    10
HIS     8
GEO     6
dtype: int32
ALUNO: 95
MAT    10
POR     2
CIE     2
HIS     6
GEO     6
dtype: int32
ALUNO: 96
MAT     0
POR     1
CIE     7
HIS    10
GEO     9
dtype: int32
ALUNO: 97
MAT     7
POR     1
CIE     7
HIS     3
GEO    10
dtype: int32
ALUNO: 98
MAT    6
POR    2
CIE    5
HIS    3
GEO    9
dtype: int32
ALUNO: 99
MAT    4
POR    2
CIE    4
HIS    5
GEO    3
dtype: int32

### Série com turmas de 1 a 5, com 20 alunos por turma, geradas aleatoriamente

In [16]:
turmas = pd.Series(np.random.randint(1, 6, 100))
turmas = turmas.apply(lambda x: x if turmas.value_counts()[x] < 20 else np.random.randint(1, 6, 1)[0])
print(turmas)

0     2
1     4
2     3
3     3
4     5
     ..
95    5
96    2
97    5
98    1
99    3
Length: 100, dtype: int64

### Criando uma grade de 100 alunos, com suas notas e turmas

In [17]:
grades = pd.Series([pd.Series([alunos[i], notas[i], turmas[i]]) for i in range(100)], name = "Grade")
for i in range(100):
    print("=======================")
    print("ALUNO: " + str(alunos[i]))
    print("NOTAS: \n" + str(notas[i]))
    print("TURMA: " + str(turmas[i]))
    print("=======================")

q11.a.check()

=======================
ALUNO: 4000
NOTAS:
MAT    6
POR    4
CIE    6
HIS    4
GEO    9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4001
NOTAS:
MAT     4
POR     8
CIE    10
HIS     3
GEO     0
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4002
NOTAS:
MAT    9
POR    1
CIE    7
HIS    8
GEO    3
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4003
NOTAS:
MAT    2
POR    1
CIE    6
HIS    3
GEO    5
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4004
NOTAS:
MAT    1
POR    9
CIE    2
HIS    3
GEO    5
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4005
NOTAS:
MAT    6
POR    6
CIE    2
HIS    0
GEO    4
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4006
NOTAS:
MAT    4
POR    1
CIE    3
HIS    4
GEO    9
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4007
NOTAS:
MAT    4
POR    4
CIE    8
HIS    6
GEO    0
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4008
NOTAS:
MAT     4
POR     7
CIE     8
HIS    10
GEO     2
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4009
NOTAS:
MAT     3
POR     1
CIE     1
HIS    10
GEO     0
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4010
NOTAS:
MAT    1
POR    0
CIE    3
HIS    7
GEO    6
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4011
NOTAS:
MAT     4
POR     1
CIE     1
HIS    10
GEO     6
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4012
NOTAS:
MAT    10
POR    10
CIE     1
HIS     8
GEO    10
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4013
NOTAS:
MAT    7
POR    9
CIE    5
HIS    6
GEO    1
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4014
NOTAS:
MAT    0
POR    2
CIE    2
HIS    9
GEO    6
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4015
NOTAS:
MAT     1
POR     6
CIE     1
HIS    10
GEO     8
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4016
NOTAS:
MAT    3
POR    9
CIE    4
HIS    9
GEO    7
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4017
NOTAS:
MAT    1
POR    3
CIE    4
HIS    2
GEO    1
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4018
NOTAS:
MAT    7
POR    8
CIE    2
HIS    5
GEO    5
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4019
NOTAS:
MAT    1
POR    1
CIE    4
HIS    7
GEO    8
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4020
NOTAS:
MAT     4
POR    10
CIE    10
HIS     9
GEO     2
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4021
NOTAS:
MAT     1
POR     1
CIE     4
HIS     4
GEO    10
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4022
NOTAS:
MAT    7
POR    0
CIE    5
HIS    1
GEO    1
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4023
NOTAS:
MAT    2
POR    1
CIE    1
HIS    5
GEO    1
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4024
NOTAS:
MAT     4
POR     2
CIE    10
HIS     1
GEO     8
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4025
NOTAS:
MAT     2
POR    10
CIE     4
HIS     9
GEO     6
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4026
NOTAS:
MAT    10
POR     1
CIE     0
HIS     4
GEO     8
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4027
NOTAS:
MAT    3
POR    7
CIE    1
HIS    1
GEO    6
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4028
NOTAS:
MAT     4
POR     8
CIE    10
HIS    10
GEO     4
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4029
NOTAS:
MAT    9
POR    3
CIE    9
HIS    7
GEO    6
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4030
NOTAS:
MAT    8
POR    4
CIE    3
HIS    8
GEO    3
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4031
NOTAS:
MAT     1
POR     9
CIE    10
HIS     6
GEO     5
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4032
NOTAS:
MAT    6
POR    3
CIE    9
HIS    0
GEO    6
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4033
NOTAS:
MAT    9
POR    7
CIE    6
HIS    2
GEO    1
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4034
NOTAS:
MAT    1
POR    2
CIE    8
HIS    4
GEO    4
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4035
NOTAS:
MAT    2
POR    0
CIE    1
HIS    3
GEO    9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4036
NOTAS:
MAT    3
POR    9
CIE    9
HIS    9
GEO    9
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4037
NOTAS:
MAT    10
POR     3
CIE     9
HIS     2
GEO     7
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4038
NOTAS:
MAT    6
POR    2
CIE    9
HIS    5
GEO    2
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4039
NOTAS:
MAT     6
POR     5
CIE     1
HIS     4
GEO    10
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4040
NOTAS:
MAT     7
POR     9
CIE     0
HIS    10
GEO    10
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4041
NOTAS:
MAT     6
POR     1
CIE     8
HIS    10
GEO     5
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4042
NOTAS:
MAT    2
POR    1
CIE    8
HIS    7
GEO    9
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4043
NOTAS:
MAT    10
POR     6
CIE    10
HIS     2
GEO     6
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4044
NOTAS:
MAT    3
POR    3
CIE    7
HIS    2
GEO    6
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4045
NOTAS:
MAT    6
POR    4
CIE    9
HIS    2
GEO    5
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4046
NOTAS:
MAT    5
POR    4
CIE    0
HIS    5
GEO    5
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4047
NOTAS:
MAT    0
POR    0
CIE    1
HIS    1
GEO    2
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4048
NOTAS:
MAT    9
POR    2
CIE    8
HIS    2
GEO    4
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4049
NOTAS:
MAT    3
POR    9
CIE    6
HIS    4
GEO    8
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4050
NOTAS:
MAT    9
POR    9
CIE    4
HIS    0
GEO    8
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4051
NOTAS:
MAT    2
POR    5
CIE    9
HIS    7
GEO    7
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4052
NOTAS:
MAT    2
POR    5
CIE    5
HIS    0
GEO    0
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4053
NOTAS:
MAT    6
POR    6
CIE    3
HIS    1
GEO    3
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4054
NOTAS:
MAT    1
POR    9
CIE    2
HIS    0
GEO    4
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4055
NOTAS:
MAT     5
POR     3
CIE     5
HIS    10
GEO    10
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4056
NOTAS:
MAT     3
POR     0
CIE     9
HIS     1
GEO    10
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4057
NOTAS:
MAT     1
POR     6
CIE    10
HIS     3
GEO     5
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4058
NOTAS:
MAT     8
POR    10
CIE     5
HIS     7
GEO     9
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4059
NOTAS:
MAT    1
POR    0
CIE    9
HIS    1
GEO    9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4060
NOTAS:
MAT    3
POR    1
CIE    0
HIS    1
GEO    0
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4061
NOTAS:
MAT     3
POR     5
CIE     9
HIS    10
GEO     4
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4062
NOTAS:
MAT     3
POR     0
CIE     3
HIS    10
GEO     1
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4063
NOTAS:
MAT    6
POR    1
CIE    7
HIS    3
GEO    4
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4064
NOTAS:
MAT     8
POR     6
CIE     9
HIS     8
GEO    10
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4065
NOTAS:
MAT    0
POR    4
CIE    4
HIS    9
GEO    3
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4066
NOTAS:
MAT    4
POR    8
CIE    8
HIS    5
GEO    2
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4067
NOTAS:
MAT    10
POR     8
CIE    10
HIS     1
GEO     1
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4068
NOTAS:
MAT    4
POR    1
CIE    4
HIS    1
GEO    8
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4069
NOTAS:
MAT     8
POR     1
CIE     2
HIS    10
GEO     9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4070
NOTAS:
MAT     3
POR     6
CIE    10
HIS     8
GEO     0
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4071
NOTAS:
MAT    6
POR    6
CIE    7
HIS    8
GEO    3
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4072
NOTAS:
MAT     6
POR     0
CIE     6
HIS     3
GEO    10
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4073
NOTAS:
MAT     5
POR     7
CIE     3
HIS     3
GEO    10
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4074
NOTAS:
MAT    5
POR    2
CIE    9
HIS    7
GEO    3
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4075
NOTAS:
MAT    2
POR    4
CIE    3
HIS    5
GEO    9
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4076
NOTAS:
MAT    3
POR    3
CIE    4
HIS    3
GEO    2
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4077
NOTAS:
MAT    5
POR    8
CIE    9
HIS    2
GEO    1
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4078
NOTAS:
MAT    8
POR    4
CIE    6
HIS    4
GEO    7
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4079
NOTAS:
MAT    7
POR    5
CIE    8
HIS    8
GEO    9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4080
NOTAS:
MAT     5
POR     0
CIE    10
HIS     7
GEO    10
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4081
NOTAS:
MAT    2
POR    8
CIE    0
HIS    6
GEO    5
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4082
NOTAS:
MAT    2
POR    5
CIE    4
HIS    2
GEO    0
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4083
NOTAS:
MAT     7
POR     1
CIE    10
HIS     5
GEO     6
dtype: int32
TURMA: 3
=======================
=======================
ALUNO: 4084
NOTAS:
MAT    3
POR    2
CIE    6
HIS    5
GEO    5
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4085
NOTAS:
MAT    5
POR    8
CIE    9
HIS    2
GEO    3
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4086
NOTAS:
MAT    8
POR    4
CIE    4
HIS    9
GEO    2
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4087
NOTAS:
MAT    5
POR    3
CIE    9
HIS    9
GEO    3
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4088
NOTAS:
MAT    4
POR    1
CIE    6
HIS    9
GEO    8
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4089
NOTAS:
MAT    9
POR    9
CIE    3
HIS    7
GEO    2
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4090
NOTAS:
MAT    10
POR    10
CIE     0
HIS     4
GEO     2
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4091
NOTAS:
MAT     5
POR     2
CIE    10
HIS     3
GEO    10
dtype: int32
TURMA: 4
=======================
=======================
ALUNO: 4092
NOTAS:
MAT    2
POR    7
CIE    5
HIS    9
GEO    6
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4093
NOTAS:
MAT    4
POR    8
CIE    7
HIS    7
GEO    8
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4094
NOTAS:
MAT     0
POR     6
CIE    10
HIS     8
GEO     6
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4095
NOTAS:
MAT    10
POR     2
CIE     2
HIS     6
GEO     6
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4096
NOTAS:
MAT     0
POR     1
CIE     7
HIS    10
GEO     9
dtype: int32
TURMA: 2
=======================
=======================
ALUNO: 4097
NOTAS:
MAT     7
POR     1
CIE     7
HIS     3
GEO    10
dtype: int32
TURMA: 5
=======================
=======================
ALUNO: 4098
NOTAS:
MAT    6
POR    2
CIE    5
HIS    3
GEO    9
dtype: int32
TURMA: 1
=======================
=======================
ALUNO: 4099
NOTAS:
MAT    4
POR    2
CIE    4
HIS    5
GEO    3
dtype: int32
TURMA: 3
=======================

CORRETO:

### 11.b.
Agora, usando a série `grades` que você criou, extraia 5 informações que podem ser úteis em uma reunião de pais, análise pedagócica, avaliações, etc.

Esta questão não possui `check`.
Mas você pode pedir dica com `q11.b.hint()`.

### Média das notas de cada aluno

In [18]:
media = grades.apply(lambda x: x[1].mean())
print("Aluno\tMédia" + "\n" + "-"*20)
for i in range(100):
    print(str(grades[i][0]) + "\t" + str(media[i]))

Aluno	Média
--------------------
4000	5.8
4001	5.0
4002	5.6
4003	3.4
4004	4.0
4005	3.6
4006	4.2
4007	4.4
4008	6.2
4009	3.0
4010	3.4
4011	4.4
4012	7.8
4013	5.6
4014	3.8
4015	5.2
4016	6.4
4017	2.2
4018	5.4
4019	4.2
4020	7.0
4021	4.0
4022	2.8
4023	2.0
4024	5.0
4025	6.2
4026	4.6
4027	3.6
4028	7.2
4029	6.8
4030	5.2
4031	6.2
4032	4.8
4033	5.0
4034	3.8
4035	3.0
4036	7.8
4037	6.2
4038	4.8
4039	5.2
4040	7.2
4041	6.0
4042	5.4
4043	6.8
4044	4.2
4045	5.2
4046	3.8
4047	0.8
4048	5.0
4049	6.0
4050	6.0
4051	6.0
4052	2.4
4053	3.8
4054	3.2
4055	6.6
4056	4.6
4057	5.0
4058	7.8
4059	4.0
4060	1.0
4061	6.2
4062	3.4
4063	4.2
4064	8.2
4065	4.0
4066	5.4
4067	6.0
4068	3.6
4069	6.0
4070	5.4
4071	6.0
4072	5.0
4073	5.6
4074	5.2
4075	4.6
4076	3.0
4077	5.0
4078	5.8
4079	7.4
4080	6.4
4081	4.2
4082	2.6
4083	5.8
4084	4.2
4085	5.4
4086	5.4
4087	5.8
4088	5.6
4089	6.0
4090	5.2
4091	6.0
4092	5.8
4093	6.8
4094	6.0
4095	5.2
4096	5.4
4097	5.6
4098	5.0
4099	3.6

### Alunos aptos a passar de ano direto. É importante notar que a média mínima para passar de ano é 6 e que os alunos podem fazer a prova de recuperação se tiverem média menor que 6 e maior que 4.

In [19]:
apto = grades.apply(lambda x: x[1].mean() >= 6)
aprovados = 0
reprovados = 0
recuperacao = 0
print("Aluno\tApto" + "\n" + "-"*20)
for i in range(100):
    if apto[i]:
        print(str(grades[i][0]) + "\t" + "APROVADO")
        aprovados += 1
    else:
        if grades[i][1].mean() >= 4:
            print(str(grades[i][0]) + "\t" + "RECUPERAÇÃO, média: " + str(grades[i][1].mean()))
            recuperacao += 1
        else:
            print(str(grades[i][0]) + "\t" + "REPROVADO, média: " + str(grades[i][1].mean()))
            reprovados += 1

Aluno	Apto
--------------------
4000	RECUPERAÇÃO, média: 5.8
4001	RECUPERAÇÃO, média: 5.0
4002	RECUPERAÇÃO, média: 5.6
4003	REPROVADO, média: 3.4
4004	RECUPERAÇÃO, média: 4.0
4005	REPROVADO, média: 3.6
4006	RECUPERAÇÃO, média: 4.2
4007	RECUPERAÇÃO, média: 4.4
4008	APROVADO
4009	REPROVADO, média: 3.0
4010	REPROVADO, média: 3.4
4011	RECUPERAÇÃO, média: 4.4
4012	APROVADO
4013	RECUPERAÇÃO, média: 5.6
4014	REPROVADO, média: 3.8
4015	RECUPERAÇÃO, média: 5.2
4016	APROVADO
4017	REPROVADO, média: 2.2
4018	RECUPERAÇÃO, média: 5.4
4019	RECUPERAÇÃO, média: 4.2
4020	APROVADO
4021	RECUPERAÇÃO, média: 4.0
4022	REPROVADO, média: 2.8
4023	REPROVADO, média: 2.0
4024	RECUPERAÇÃO, média: 5.0
4025	APROVADO
4026	RECUPERAÇÃO, média: 4.6
4027	REPROVADO, média: 3.6
4028	APROVADO
4029	APROVADO
4030	RECUPERAÇÃO, média: 5.2
4031	APROVADO
4032	RECUPERAÇÃO, média: 4.8
4033	RECUPERAÇÃO, média: 5.0
4034	REPROVADO, média: 3.8
4035	REPROVADO, média: 3.0
4036	APROVADO
4037	APROVADO
4038	RECUPERAÇÃO, média: 4.8
4039	RECUPERAÇÃO, média: 5.2
4040	APROVADO
4041	APROVADO
4042	RECUPERAÇÃO, média: 5.4
4043	APROVADO
4044	RECUPERAÇÃO, média: 4.2
4045	RECUPERAÇÃO, média: 5.2
4046	REPROVADO, média: 3.8
4047	REPROVADO, média: 0.8
4048	RECUPERAÇÃO, média: 5.0
4049	APROVADO
4050	APROVADO
4051	APROVADO
4052	REPROVADO, média: 2.4
4053	REPROVADO, média: 3.8
4054	REPROVADO, média: 3.2
4055	APROVADO
4056	RECUPERAÇÃO, média: 4.6
4057	RECUPERAÇÃO, média: 5.0
4058	APROVADO
4059	RECUPERAÇÃO, média: 4.0
4060	REPROVADO, média: 1.0
4061	APROVADO
4062	REPROVADO, média: 3.4
4063	RECUPERAÇÃO, média: 4.2
4064	APROVADO
4065	RECUPERAÇÃO, média: 4.0
4066	RECUPERAÇÃO, média: 5.4
4067	APROVADO
4068	REPROVADO, média: 3.6
4069	APROVADO
4070	RECUPERAÇÃO, média: 5.4
4071	APROVADO
4072	RECUPERAÇÃO, média: 5.0
4073	RECUPERAÇÃO, média: 5.6
4074	RECUPERAÇÃO, média: 5.2
4075	RECUPERAÇÃO, média: 4.6
4076	REPROVADO, média: 3.0
4077	RECUPERAÇÃO, média: 5.0
4078	RECUPERAÇÃO, média: 5.8
4079	APROVADO
4080	APROVADO
4081	RECUPERAÇÃO, média: 4.2
4082	REPROVADO, média: 2.6
4083	RECUPERAÇÃO, média: 5.8
4084	RECUPERAÇÃO, média: 4.2
4085	RECUPERAÇÃO, média: 5.4
4086	RECUPERAÇÃO, média: 5.4
4087	RECUPERAÇÃO, média: 5.8
4088	RECUPERAÇÃO, média: 5.6
4089	APROVADO
4090	RECUPERAÇÃO, média: 5.2
4091	APROVADO
4092	RECUPERAÇÃO, média: 5.8
4093	APROVADO
4094	APROVADO
4095	RECUPERAÇÃO, média: 5.2
4096	RECUPERAÇÃO, média: 5.4
4097	RECUPERAÇÃO, média: 5.6
4098	RECUPERAÇÃO, média: 5.0
4099	REPROVADO, média: 3.6

### Quantidade de alunos aprovados, reprovados e em recuperação
### Este número é importante para saber se a escola está indo bem ou mal de acordo com o ranking do IFNE (Instituto Fictício Não Existente), e se é necessário melhorar a qualidade do ensino.

In [20]:
print("Aprovados: " + str(aprovados))
print("Reprovados: " + str(reprovados))
print("Recuperação: " + str(recuperacao))
Nota_Escola = (aprovados + recuperacao/2)/100
print("Nota IFNE: " + str(Nota_Escola))

if Nota_Escola < 0.6:
    print("A escola está indo mal")
else:
    print("A escola está indo bem")

Aprovados: 29
Reprovados: 22
Recuperação: 49
Nota IFNE: 0.535
A escola está indo mal

### Ranking de disciplinas com as melhores médias

In [21]:
media_MAT = (grades.apply(lambda x: x[1]["MAT"])).mean()
media_POR = (grades.apply(lambda x: x[1]["POR"])).mean()
media_CIE = (grades.apply(lambda x: x[1]["CIE"])).mean()
media_HIS = (grades.apply(lambda x: x[1]["HIS"])).mean()
media_GEO = (grades.apply(lambda x: x[1]["GEO"])).mean()
medias = pd.Series([media_MAT, media_POR, media_CIE, media_HIS, media_GEO], index = disciplina)
medias = medias.sort_values(ascending = False)
print("Disciplina\tMédia" + "\n" + "-"*20)
for i in range(5):
    print(str(medias.index[i]) + "\t" + str(medias[i]))

Disciplina	Média
--------------------
CIE	5.56
GEO	5.37
HIS	5.21
MAT	4.62
POR	4.32

### Aluno com média abaixo de 2.5.
### Esses alunos requerem um acompanhamento especial, pois estão com dificuldades em aprender, de acordo com o IFNE.

In [22]:
alunos_abaixo_2 = grades.apply(lambda x: x[1].mean() < 2.5)
print("Aluno\tMédia" + "\n" + "-"*20)
for i in range(100):
    if alunos_abaixo_2[i]:
        print(str(grades[i][0]) + "\t" + str(grades[i][1].mean()))

Aluno	Média
--------------------
4017	2.2
4023	2.0
4047	0.8
4052	2.4
4060	1.0

### 11.c.
Faça uma breve análise sobre a utilidade e limitações de uma série `pandas`. Também inclua uma opinião pessoal curta se gostou ou não dessa estrutura.

Esta questão não possui `check`.
Mas você pode pedir dica com `q11.c.hint()`.

#### Resposta:

### Essa etrutura de dados série é muito útil e versátil para trabalhar com dados unidimensionais. Ela oferece muitos recursos úteis e é fácil de usar. Como foi meu primeiro contato tive dificuldades na questão 11, mas consegui resolver depois de várias tentativas.
### Gostei de usar mas prefiro trabalhar com dataframes, pois é mais fácil de visualizar os dados.